name: expenses_app_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  build_runner: ^2.4.9
  calendar_date_picker2: ^1.0.2
  cloud_firestore: ^5.0.1
  connectivity: ^3.0.6
  csv: ^6.0.0
  file_picker: ^8.0.3
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.19.0
  url_launcher: ^6.2.6
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
