name: expenses_app_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  csv: ^6.0.0
  file_picker: ^8.0.3
  firebase_core: ^2.31.1
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
