// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC40C3F_XehAafSSgBPSDFRq3mmUW6ttvo',
    appId: '1:465105732273:web:12ff69cbde38906c39d890',
    messagingSenderId: '465105732273',
    projectId: 'expences-app-f71fb',
    authDomain: 'expences-app-f71fb.firebaseapp.com',
    storageBucket: 'expences-app-f71fb.appspot.com',
    measurementId: 'G-FGJY7TEJWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw3GdS7UyQ2h_sXKd1wuRN5e3VgFFjTmk',
    appId: '1:465105732273:android:00930045b3969f3839d890',
    messagingSenderId: '465105732273',
    projectId: 'expences-app-f71fb',
    storageBucket: 'expences-app-f71fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrqT_zXZuuVltrfWELtYbf9ywB9AIT728',
    appId: '1:465105732273:ios:f257cf6c189f86f639d890',
    messagingSenderId: '465105732273',
    projectId: 'expences-app-f71fb',
    storageBucket: 'expences-app-f71fb.appspot.com',
    iosBundleId: 'com.example.expencesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrqT_zXZuuVltrfWELtYbf9ywB9AIT728',
    appId: '1:465105732273:ios:f257cf6c189f86f639d890',
    messagingSenderId: '465105732273',
    projectId: 'expences-app-f71fb',
    storageBucket: 'expences-app-f71fb.appspot.com',
    iosBundleId: 'com.example.expencesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC40C3F_XehAafSSgBPSDFRq3mmUW6ttvo',
    appId: '1:465105732273:web:7c5f695815078f9b39d890',
    messagingSenderId: '465105732273',
    projectId: 'expences-app-f71fb',
    authDomain: 'expences-app-f71fb.firebaseapp.com',
    storageBucket: 'expences-app-f71fb.appspot.com',
    measurementId: 'G-BP3DRQ7YMD',
  );
}
